-- Liquidation Nation DC bootstrap
-- Run this whole file once in Supabase SQL Editor

-- Liquidation Nation DC - initial schema

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'product_status') then
    create type product_status as enum ('draft', 'in_stock', 'out_of_stock', 'hidden');
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'product_condition') then
    create type product_condition as enum ('new', 'open_box', 'used');
  end if;
end $$;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order integer not null default 100,
  is_active boolean not null default true
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text,
  category_id bigint references public.categories(id) on delete set null,
  price numeric(12,2),
  retail_price numeric(12,2),
  condition product_condition not null default 'new',
  quantity integer not null default 0 check (quantity >= 0),
  status product_status not null default 'draft',
  is_featured boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0
);

-- Explicit grants for Data API roles (important for projects with default privileges disabled)
grant usage on schema public to anon, authenticated, service_role;

grant select
  on table public.categories, public.products, public.product_images
  to anon;

grant select, insert, update, delete
  on table public.categories, public.products, public.product_images
  to authenticated, service_role;

grant usage, select
  on all sequences in schema public
  to anon, authenticated, service_role;

create index if not exists idx_categories_sort_order on public.categories(sort_order);
create index if not exists idx_products_status on public.products(status);
create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_products_updated_at on public.products(updated_at desc);
create index if not exists idx_products_search_title on public.products using gin (to_tsvector('english', coalesce(title, '')));
create index if not exists idx_product_images_product_id on public.product_images(product_id);
create index if not exists idx_product_images_sort on public.product_images(product_id, sort_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;

-- Public storefront can read active categories
drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
  on public.categories
  for select
  to public
  using (is_active = true);

-- Authenticated admins can fully manage categories
drop policy if exists "Authenticated manage categories" on public.categories;
create policy "Authenticated manage categories"
  on public.categories
  for all
  to authenticated
  using (true)
  with check (true);

-- Public storefront can read only visible products
drop policy if exists "Public can read visible products" on public.products;
create policy "Public can read visible products"
  on public.products
  for select
  to public
  using (status in ('in_stock', 'out_of_stock'));

-- Authenticated admins can fully manage products
drop policy if exists "Authenticated manage products" on public.products;
create policy "Authenticated manage products"
  on public.products
  for all
  to authenticated
  using (true)
  with check (true);

-- Public storefront can read images for visible products
drop policy if exists "Public can read product images" on public.product_images;
create policy "Public can read product images"
  on public.product_images
  for select
  to public
  using (
    exists (
      select 1
      from public.products p
      where p.id = product_images.product_id
        and p.status in ('in_stock', 'out_of_stock')
    )
  );

-- Authenticated admins can fully manage product images
drop policy if exists "Authenticated manage product images" on public.product_images;
create policy "Authenticated manage product images"
  on public.product_images
  for all
  to authenticated
  using (true)
  with check (true);

-- Storage setup (run once). Bucket must be public for direct image URLs.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "Public read product images bucket" on storage.objects;
create policy "Public read product images bucket"
  on storage.objects
  for select
  to public
  using (bucket_id = 'product-images');

drop policy if exists "Authenticated manage product images bucket" on storage.objects;
create policy "Authenticated manage product images bucket"
  on storage.objects
  for all
  to authenticated
  using (bucket_id = 'product-images')
  with check (bucket_id = 'product-images');


-- Seed base categories
insert into public.categories (name, slug, sort_order, is_active)
values
  ('Tools', 'tools', 10, true),
  ('Landscape tools', 'landscape-tools', 20, true),
  ('Vanity''s', 'vanitys', 30, true),
  ('Appliances', 'appliances', 40, true),
  ('Lights', 'lights', 50, true),
  ('Doors and windows', 'doors-and-windows', 60, true),
  ('Bathtub, shower set & base', 'bathtub-shower-set-base', 70, true),
  ('Sink', 'sink', 80, true),
  ('For Kids', 'for-kids', 90, true)
on conflict (slug) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

